<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 static/models/nintendo-ds-lite.glb
-->

<script lang="ts">
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/static/models/nintendo-ds-lite.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T is={gltf.nodes.Root_Bone} />
    <T is={gltf.nodes.Pad_Bone} />
    <T is={gltf.nodes.Trigger_R_Bone} />
    <T is={gltf.nodes.Trigger_L_Bone} />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
